version: '3'

volumes:
  db-data:
    driver: local

services:
  app:
    build:
      context: .
    container_name: personnel
    depends_on:
      - db
    ports:
      - '8080:8080'
      - '5005:5005'
  db:
    image: postgres:15.1-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'